# Generated by Django 2.2 on 2019-05-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190514_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body_text',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(max_length=200),
        ),
    ]
