# Generated by Django 2.2 on 2019-05-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190514_0627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='body_text',
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.TextField(),
        ),
    ]
