# Generated by Django 2.2 on 2019-05-13 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bat', '0002_auto_20190513_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mcq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(max_length=50, unique=True)),
                ('choice1', models.CharField(max_length=50, unique=True)),
                ('choice2', models.CharField(max_length=50, unique=True)),
                ('choice3', models.CharField(max_length=50, unique=True)),
                ('choice4', models.CharField(max_length=50, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
