# Generated by Django 2.2 on 2019-05-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat', '0004_auto_20190513_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='bat',
            name='enable_when_question_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mcq',
            name='enable_when_question_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
