# Generated by Django 2.2 on 2019-05-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat', '0005_auto_20190513_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='bat',
            name='is_dependent_question_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Ans',
        ),
    ]
