# Generated by Django 2.2 on 2019-05-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat', '0007_auto_20190529_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='bat_textquestions',
            name='s_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
