# Generated by Django 2.2 on 2019-05-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bat1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers_Bat1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers1', models.CharField(max_length=200)),
                ('answers2', models.CharField(max_length=200)),
                ('answers3', models.CharField(max_length=200)),
                ('answers4', models.CharField(max_length=200)),
                ('answers5', models.CharField(max_length=200)),
                ('answers6', models.CharField(max_length=200)),
                ('answers7', models.CharField(max_length=200)),
                ('answers8', models.CharField(max_length=200)),
                ('answers9', models.CharField(max_length=200)),
                ('answers10', models.CharField(max_length=200)),
                ('answers11', models.CharField(max_length=200)),
                ('answers12', models.CharField(max_length=200)),
            ],
        ),
    ]
